# This is a basic workflow to help you get started with Actions

# Inspiration for frontend workflow taken from Rupesh Tiwari:
# https://www.rupeshtiwari.com/setup-ci-cd-for-angular-app-with-github-action/


name: CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: [ '*' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_backend:
    if: ${{ false }}  # disable for now
    name: Build backend
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: leocode-backend
    defaults:
      run:
        working-directory: ./leocode-backend
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Package
        run: mvn package -DskipTests
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build . -f src/main/docker/Dockerfile.jvm --tag $IMAGE_NAME
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo ${{ github.ref }} | cut -c11-)
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  build_testing:
    if: ${{ false }}  # disable for now
    name: Build testing
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: leocode-testing-api
    defaults:
      run:
        working-directory: ./testing-api
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Package
        run: mvn package -DskipTests
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build . -f src/main/docker/Dockerfile.jvm --tag $IMAGE_NAME
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo ${{ github.ref }} | cut -c11-)
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: leocode-frontend
    defaults:
      run:
        working-directory: ./frontend
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version:
            ${{matrix.node-version}}
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build . -f Dockerfile --tag $IMAGE_NAME
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo ${{ github.ref }} | cut -c11-)
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION