name: GitHub Pages CD

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build âš™
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: quirinecker/asciidoctor-convert-action@main
        with:
          slides: true
          inputPath: docs
          outputPath: dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ github.TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
